name: Build
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]
      fail-fast: true
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn run build
      - run: yarn test
