name: PR
on: pull_request
jobs:
  conventional:
    name: Conventional PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install --immutable
      - uses: beemojs/conventional-pr-action@v2
        with:
          auto-install: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
